[package]
name = "server-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
warp = "*"
futures-util = "*"
rand = "*"
tracing-mutex = "*"
serde_json = "*"
serde = { version = "*", features = ["derive"] }
futures = "*"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
